const sticker = (pack, id, extension, alt) => ({
  id: `${pack}-${id}`,
  url: `/stickers/${pack}/${id}.${extension}`,
  alt,
});

export const STICKER_PACKS = {
  Noto: [
    sticker('noto', 'ghost', 'svg', 'ghost'),
    sticker('noto', 'alien', 'svg', 'alien'),
    sticker('noto', 'party', 'svg', 'party'),
    sticker('noto', 'explode', 'svg', 'mind blown'),
    sticker('noto', 'joy', 'svg', 'joy'),
    sticker('noto', 'smirk', 'svg', 'smirk'),
    sticker('noto', 'nerd', 'svg', 'nerd'),
    sticker('noto', 'think', 'svg', 'thinking'),
    sticker('noto', 'skull', 'svg', 'skull'),
    sticker('noto', 'rocket', 'svg', 'rocket'),
    sticker('noto', 'fire', 'svg', 'fire'),
    sticker('noto', 'sparkles', 'svg', 'sparkles'),
    sticker('noto', 'eyes', 'svg', 'eyes'),
    sticker('noto', 'clap', 'svg', 'clap'),
  ],
  Twemoji: [
    sticker('twemoji', 'ghost', 'svg', 'ghost'),
    sticker('twemoji', 'alien', 'svg', 'alien'),
    sticker('twemoji', 'fire_heart', 'svg', 'heart on fire'),
    sticker('twemoji', 'party', 'svg', 'party'),
    sticker('twemoji', 'explode', 'svg', 'mind blown'),
    sticker('twemoji', 'joy', 'svg', 'joy'),
    sticker('twemoji', 'smirk', 'svg', 'smirk'),
    sticker('twemoji', 'nerd', 'svg', 'nerd'),
    sticker('twemoji', 'think', 'svg', 'thinking'),
    sticker('twemoji', 'skull', 'svg', 'skull'),
    sticker('twemoji', 'rocket', 'svg', 'rocket'),
    sticker('twemoji', 'fire', 'svg', 'fire'),
    sticker('twemoji', 'sparkles', 'svg', 'sparkles'),
    sticker('twemoji', 'eyes', 'svg', 'eyes'),
    sticker('twemoji', 'clap', 'svg', 'clap'),
  ],
  Fluent3D: [
    sticker('fluent', 'ghost', 'png', 'ghost'),
    sticker('fluent', 'alien', 'png', 'alien'),
    sticker('fluent', 'fire_heart', 'png', 'heart on fire'),
    sticker('fluent', 'party', 'png', 'party'),
    sticker('fluent', 'explode', 'png', 'mind blown'),
    sticker('fluent', 'joy', 'png', 'joy'),
    sticker('fluent', 'smirk', 'png', 'smirk'),
    sticker('fluent', 'nerd', 'png', 'nerd'),
    sticker('fluent', 'think', 'png', 'thinking'),
    sticker('fluent', 'skull', 'png', 'skull'),
    sticker('fluent', 'rocket', 'png', 'rocket'),
    sticker('fluent', 'fire', 'png', 'fire'),
    sticker('fluent', 'sparkles', 'png', 'sparkles'),
    sticker('fluent', 'eyes', 'png', 'eyes'),
    sticker('fluent', 'heart', 'png', 'heart'),
  ],
};
